export class InspeccionesComerciales {
	codigoRegistro: number;
    codigoCarga: string;
    oficinaComercial: string;
    generoUsuario: string;
    cus: string;
    ruta: string;
    itin: string;
    tipsum: string;
    fechaEmision: string;
    observacion: string;
    nombreRazon: string;
    leRuc: string;
    telefonoFax: string;
    codAbastecimiento: string;
    referenciaDireccion: string;
    cua : string;
    medidor: string;
    diametroMedidor: string;
    ultLectura: string;
    ptoMedia: string;				
    acom: string;
    nisRad: number;
    numOS: number;
    tipOS : string;
    fechaResolucion: string;
    codEmpleado: string;				
    fechaVisita: string;				
    coAccejec: string;				
    serv: string;					
    servDT : string;					
    caja: string;					
    estadoCaja: string;				
    cnxCon : string;					
    cxCDT : string;					
    lecturaMedidor: string;			
    estMedidorEncontrado1: string;	
    estMedidorEncontrado2: string;	
    estMedidorEncontrado3 : string;	
    prescinto : string;				
    fugaCaja : string;				
    nroConexiones: string;			
    medidorEncontrado2: string;		
    medidorEncontrado3: string;		
    niple2 : string;					
    niple3 : string;					
    valvulas : string;				
    disposit : string;				
    clandes : string;				
    niv_finc : string;				
    estado : string;					
    n_habit : string;				
    uu_ocup : string;				
    soc_ocup : string;				
    dom_ocup : string;				
    com_ocup : string;				
    ind_ocup : string;				
    est_ocup : string;				
    uu_docup : string;				
    soc_desc : string;				
    dom_desc : string;				
    com_desc : string;				
    ind_desc : string;				
    est_desc : string;				
    uso_unic : string;				
    calle : string;
    numero : string;
    duplicad : string;
    mza : string;
    lote : string;
    cgv : string;
    urbaniza : string;
    distrito : string;
    calle_c : string;				
    num_c : string;					
    dupli_c : string;				
    mza_c : string;					
    lote_c : string;					
    urb_c : string;					
    ref_c : string;					
    dist_c : string;					
    atendio : string;				
    paterno: string;					
    materno : string;				
    nombre : string;					
    razsoc : string;					
    dni : string;					
    telef : string;					
    fax : string;					
    ruc : string;					
    inod_b: string;					
    inod_f : string;					
    inod_cl : string;				
    lava_b : string;					
    lava_f : string;					
    lava_cl : string;				
    duch_b : string;					
    duch_f : string;					
    duch_cl : string;				
    urin_b : string;					
    urin_f : string;					
    urin_cl : string;				
    grifo_b : string;				
    grifo_f : string;				
    grifo_cl : string;				
    ciste_b : string;				
    ciste_f : string;				
    ciste_cl : string;				
    tanqu_b : string;				
    tanqu_f : string;				
    tanqu_cl : string;				
    pisc_b : string;					
    pisc_f : string;					
    pisc_cl : string;				
    bidet_b : string;				
    bidet_f : string;				
    bidet_cl : string;				
    abast : string;					
    ptome_ca : string;				
    num_p : string;					
    dup_p : string;					
    mza_p : string;					
    lote_p : string;					
    observ : string;					
    observm1 : string;				
    observm2 : string;				
    cota_sum_c : string;				
    pisos_c : string;			
    cod_ubic_c : string;				
    fte_conexion_c : string;		
    cup_c : string;				
    cota_sum : string;			
    pisos : string;				
    cod_ubic: string;				
    fte_conexion : string;		
    cup : string;				
    devuelto : string;			
    date_d : string;				
    prior : string;				
    actualiza : string;
    date_c: Date;
    resuelto : string;			
    multi : string;				
    parcial : string;			
    fte_cnx : string;			
    cota_sumc : string;			
    pisosc : string;				
    cod_ubicc : string;			
    fte_cnxc: string;			
    cupc : string;				
    hora_i : string;				
    hora_f : string;				
    valv_e_tlsc : string;			
    mat_valv_e : string;				
    valv_s_p : string;				
    mat_valv_s : string;
    sector: number;
    cup_pred: string;
    aol: number;
    ciclo: string;
    nreclamo: string;
    celular_cli: number;
    fax_cli: number;
    niv_predio: number;
    nse_pre: string;
    soc_ocup_cat : number;
    dom_ocup_cat : number;
    com_ocup_cat : number;
    ind_ocup_cat : number;
    est_ocup_cat : number;
    soc_desoc_cat : number;
    dom_desoc_cat : number;
    com_desoc_cat : number;
    ind_desoc_cat : number;
    est_desoc_cat : number;
    est_sum : string;
    fte_conex : string;
    ubic_pred : string;
    dia_conex : number;
    cota_conex : number;
    disp_seg : string;
    tip_lec : string;
    hor_abasc : string;
    nia : number;
    dia_alcan : string;
    fte_alcan : string;
    ubic_alcan : string;
    tip_suelo_alca: string;
    tip_descar_alc: string;
    cotah_alcan : number;
    cotav_alcan : number;
    long_alcan : number;
    profund_alcan : number;
    tr_grasas : number;
    sistrat : string;
    mat_tapa_alcan: string;
    est_tapa_alcan: string;
    mat_caja_alcan: string;
    est_caja_alcan: string;
    mat_tub_alcan : string;
    est_tub_alcan : string;
    email : string; 
    cel_cli_c : number;			
    telf_emp : number;	
    piso_dpto_f : string; 		
    sector_f : number;
    fte_finca : string; 			
    nse_f : string; 				
    obs_f : string; 					
    corr_cup : string; 				
    pred_no_ubic : string; 		
    var_act_predio: string; 			
    inspec_realiz : string; 		
    mot_no_ing : string; 
    dia_conex_agua: number; 
    imposibilidad : string; 		
    seguro_tap : string; 		
    est_tapa : string; 			
    inci_medidor : string; 		
    acceso_inmueb : string;
    obs_atendio : string; 		
    cartografia : string; 			
    mnto_cartog : string; 			
    corr_cup_f : string; 		
    num_med : string; 			
    dia_med : string; 			
    cnx2_con : string; 				
    cnx3_con : string; 				
    dia_med2: string; 			
    dia_med3 : string;
    lec_med2 : number; 			
    lec_med3 : number; 
    cota_hor_des : number; 	
    cota_ver_des : number; 
    long_cnx_des : number; 
    prof_cja_des : number; 
    tip_suelo_des : string; 			
    ind_tram_des : string; 			
    dia_conex_des : string; 			
    silo : string; 					
    est_tapa_des : string; 			
    est_caja_des : string; 			
    est_tub_des : string; 			
    tip_mat_tap_d : string; 			
    tip_mat_caj_d : string; 			
    tip_mat_tub_d : string; 			
    sis_trat_res : string; 			
    tip_des_des : string; 			
    clandes_des : string;
    cod_sup : number;			
    cod_digit : number;		
}