export enum AccionesMantPersonal {
  REGISTRAR_PERSONAL = 'RP',
  MODIFICAR_PERSONAL = 'MP',
  DAR_ALTA_PERSONAL = 'AP',
  CESAR_PERSONAL = 'CP',
  CARGAR_MASIVA_PERSONAL = 'CM',
  VER_DETALLE_PERSONAL = 'DP'
}
