export enum EstadoCargaTrabajo {
 POR_ENVIAR = 'PE',
 ENVIADO_SEDAPAL = 'ES',
 OBSERVADO_SEDAPAL = 'OS',
 ANULADO = 'AN',
 CERRADO = 'CE',
 ACEPTADO_CONTRATISTA = 'AC',
 ENVIADO_CONTRATISTA = 'EC',
 OBSERVADO_CONTRATISTA = 'OC',
 ENVIADO_PARCIAL_CONTRATISTA = 'EPC'
}
